### ISSUE TITLE
osx-arm64/maturin-0.12.4-py39h5161555_0.tar.bz2 contains x86_64 only executable

### ISSUE THREAD

**Issue by slonik-az** [conda-forge/maturin-feedstock#44]
- [ X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

## Problem
The package for `osx-arm64` contains the executable that is `x86_64` only instead of `arm64` or `universal binary`. This causes problems building programs like [polars](https://github.com/pola-rs/polars).

## How to reproduce
1. Download the `maturin` package 
`https://anaconda.org/conda-forge/maturin/0.12.4/download/osx-arm64/maturin-0.12.4-py39h5161555_0.tar.bz2`

2. Untar it on an Apple machine

3. Show the type of the binary
```
$ file bin/maturin

bin/maturin: Mach-O 64-bit executable x86_64
```
This is `x86_64` only binary that runs on Apple Silicon (M1) via Rosetta and screws up some of the build architecture parameters. I had to `pip` install maturin to get a universal binary that works fine.

**Comment by messense** [comment]
Closing as won't fix, please try newer versions. Feel free to reopen if it still occurs.
